src/cbor/encoding.c, src/cbor/internal/encoders.c, src/cbor/internal/loaders.c
#ifdef checks should be #if.  This should fix part of #5, and is an alternative to #8, which requires CMake.
=> Fix IS_BIG_ENDIAN tests.

src/cbor/arrays.h
=> adjust documentation to indicate that indexes start at 0

doc/source/conf.py
=> Fix RTD docs

Doxyfile
=> Fix doxy docs version number

CHANGELOG.md, src/CMakeLists.txt, src/libcbor.pc.in
Fixes #34 
Thank you, @jvymazal !
=> Fix Linux installation dirs depending on architecture

CMakeLists.txt
=> Fix MinGW builds

.travis.yml
=> Disable ARM builds

CHANGELOG.md, src/cbor/arrays.c, src/cbor/bytestrings.c, src/cbor/common.h, src/cbor/floats_ctrls.c, src/cbor/floats_ctrls.h, src/cbor/ints.c, src/cbor/ints.h, src/cbor/maps.c, src/cbor/strings.c, src/cbor/strings.h, src/cbor/tags.c, src/cbor/tags.h, test/cpp_linkage_test.cpp, test/memory_allocation_test.c
Fixes #84 
It would be nice to have a fuzzing test and more complicated scenarios for failing malloc issues to ensure memory correctness.
Filed #86 and #87 to follow up
=> Handle malloc failures in constructors and builders

src/cbor/streaming.c
=> Fixed several incorrect comments

CHANGELOG.md, CMakeLists.txt, src/cbor/internal/encoders.c, src/cbor/internal/loaders.c
=> Fix unaligned reads and writes when using endian.h or running big-endian

doc/source/api/item_reference_counting.rst, doc/source/api/type_0_1.rst, doc/source/api/type_7.rst, doc/source/conf.py, doc/source/internal.rst, doc/source/rfc_conformance.rst
=> Documentation fixes

CHANGELOG.md, src/cbor/encoding.c, test/cbor_serialize_test.c, test/type_7_encoders_test.c
=> Fix half-float NaN encoding

CHANGELOG.md, CMakeModules/FindCJSON.cmake, CMakeModules/LibFindMacros.cmake, examples/CMakeLists.txt
This also fixes a cmake warning when cjson is not available
=> Fix potentially incorrect cjson include

oss-fuzz/cbor_load_fuzzer.cc
Oversight in https://github.com/PJK/libcbor/pull/134
=> Fix fuzzer realloc

oss-fuzz/cbor_load_fuzzer.cc
Hi, Pavel,
In my last PR I forgot that NULL should be an allowed argument to limited_free. This has caused your Github CI to fail for the task "fuzz".
I'm correcting this in this PR, and could you make sure at least all CIs are green before you merge? Thank you.
=> allow NULL for limited_free

oss-fuzz/cbor_load_fuzzer.cc
=> Oss-fuzz: Revert to per-alloc size limit only

CNAME, doc/doxy_frontpage.md, doc/source/getting_started.rst
Drop MinGW instructions (haven't touched them in 5 yrs). Update prebuilt package infos.
Fixes #150
=> Fix "Getting started docs"

doc/source/streaming/decoding.rst
=> Fix typo in stream decoding example

CHANGELOG.md, src/cbor.c, src/cbor/serialization.c, src/cbor/tags.c, test/copy_test.c, test/type_6_test.c
=> Fix cbor_tag_item reference counting

CHANGELOG.md, src/CMakeLists.txt
=> Explicitly link math library

src/cbor/data.h
A clear and concise description of what the PR does and why.
=> Fix spelling error in comment.

Bazel.md
A clear and concise description of what the PR does and why.
=> Add Bazel build instructions.

doc/source/requirements.txt
Reverts PJK/libcbor#187
Breaks doc build
=> Revert "Bump urllib3 from 1.25.8 to 1.26.5 in /doc/source"

CHANGELOG.md, src/cbor/serialization.c, src/cbor/serialization.h, test/cbor_serialize_test.c
See https://github.com/PJK/libcbor/pull/205
=> Merge #205 w/ formatting fixes

codecov.yml
Fix e.g. https://github.com/PJK/libcbor/pull/212#issuecomment-1071864837
=> Make Codecov less sensitive

CHANGELOG.md, src/cbor/encoding.c, test/float_ctrl_encoders_test.c
Merge https://github.com/PJK/libcbor/pull/208 w/ minor formatting tweaks + extra tests
=> Half-float encoding improvements; float encoding test improvements

codecov.yml
https://github.com/PJK/libcbor/commit/90a93674c2353fc445cd2ee17bda064de31309cc doesn't seem to have worked
=> Ignore tests for codecov, attempt 2

README.md, doc/source/api.rst, doc/source/rfc_conformance.rst
switch to ssl/https scheme in order to avoid 404
=> Update links to use https

.circleci/config.yml
E.g. https://app.circleci.com/pipelines/github/PJK/libcbor/76/workflows/b8c43edf-b21b-4ef0-bee6-59608a54eeba/jobs/343
=> Improve error message on CI format check failure

test/array_encoders_test.c, test/array_test.c, test/assertions.c, test/assertions.h, test/bad_inputs_test.c, test/bytestring_encoders_test.c, test/bytestring_test.c, test/callbacks_test.c, test/cbor_serialize_test.c, test/cbor_stream_decode_test.c, test/copy_test.c, test/float_ctrl_encoders_test.c, test/fuzz_test.c, test/map_encoders_test.c, test/map_test.c, test/memory_utils_test.c, test/negint_encoders_test.c, test/negint_test.c, test/pretty_printer_test.c, test/stack_over_limit_test.c, test/stream_expectations.h, test/string_encoders_test.c, test/string_test.c, test/tag_encoders_test.c, test/tag_test.c, test/test_allocator.c, test/test_allocator.h, test/uint_encoders_test.c, test/uint_test.c, test/unicode_test.c
=> Fix test assertions on size_t

.circleci/config.yml, test/CMakeLists.txt, test/cbor_serialize_test.c, test/float_ctrl_encoders_test.c, test/test_allocator.c
Discovered https://github.com/PJK/libcbor/issues/271
Closes #270 
Partially solves #213
=> Set up Windows CI including tests, make tests cross-platform

CHANGELOG.md, README.md, doc/source/api/item_types.rst, doc/source/development.rst, doc/source/index.rst, doc/source/internal.rst, doc/source/standard_conformance.rst, examples/readfile.c, src/cbor/common.h, src/cbor/internal/loaders.c
Fixes https://github.com/PJK/libcbor/issues/269
=> Update docs for STD94

src/cbor.c, src/cbor/maps.c, test/pretty_printer_test.c
- To unblock https://github.com/PJK/libcbor/pull/281
=> Add a unit test + minor fixes for cbor_describe

test/test_allocator.c
=> Fix missing (void) in tests

doc/source/development.rst
Also test new hook integration, RTD should run a check on the PR
=> Fix sphinx format warning

CMakeLists.txt, src/cbor.c
Fixes https://github.com/PJK/libcbor/issues/311
=> Make MSVC w/ /sdl work

oss-fuzz/cbor_load_fuzzer.cc
=> Fix wrong fopen mode in fuzzer

.cirrus.yml
=> Update cirrus FreeBSD to 14.2

doc/source/requirements.txt
=> Update python requirements

examples/cbor2cjson.c
=> Update example formatting (clang changed)

release.sh
Commit no longer needed with PR setup from https://github.com/PJK/libcbor/pull/348
=> Fix small typo in release script

test/callbacks_test.c
=> Fix failing 32 bit tests due to cmocka macro repeating stack pushes

CHANGELOG.md, CMakeLists.txt, src/cbor/common.c, test/float_ctrl_test.c
Fixes https://github.com/PJK/libcbor/issues/352
=> Fix float_ctrl ctr getter assertions failing in debug mode

CHANGELOG.md, README.md, examples/CMakeLists.txt, examples/cbor_sequence.c
=> Add CBOR sequences example

CHANGELOG.md, CMakeLists.txt, src/cbor/common.h
Fixes https://github.com/PJK/libcbor/issues/247
=> Add [[nodiscard]] support and auto-update to C23 in cmake

.circleci/config.yml
Fixes https://github.com/PJK/libcbor/issues/334
=> Configure ctest on to export the test results to CircleCI

CHANGELOG.md, doc/source/api/item_reference_counting.rst, src/cbor.c, src/cbor.h, src/cbor/arrays.c, test/copy_test.c
Fixes https://github.com/PJK/libcbor/issues/51
=> Add cbor_copy_definite

.cirrus.yml, doc/source/getting_started.rst
See https://github.com/PJK/libcbor/issues/372
=> Add a doc note on lto linking
