PJK/libcbor

src/CMakeLists.txt

Most libraries are using a versioned SONAME to track API changes. When
they don't, we usually use a SOVERSION of 0. When willing to commit to
some API stability, SOVERSION and VERSION should be updated to more
adequate values (VERSION could match the library version, assuming it
follows the major.minor.patch convention and SOVERSION could be
major.minor since CMake doesn't support libtool versioning scheme with
age).
With this change CMake will install the library as
libcbor.so.0.0.0. libcbor.so.0 will be a symlink to the library for
other applications, to be found with the dynamic linker. libcbor.so will
be a symlink to libcbor.so.0 for use by the linker (ld).

build: enable use of versioned SONAME

---

CMakeLists.txt
src/cbor/internal/encoders.c
src/cbor/internal/loaders.c

The test that was in the source code itself was not working on OSX and incorrectly used big-endian. As CMake is already used, I changed the code to use that.

Use CMake for big-endian test

---

src/cbor/callbacks.c
src/cbor/callbacks.h

With dummy callback bundle declared as static variable in the header file, some projects do not link with the static library due to `cbor_null_*_callback` symbols being unresolved.
Declaring the bundle `extern` in the header file and defining it in the source file resolved this problem.

Remove static declaration of the dummy callback bundle from header

---

CHANGELOG.md
examples/readfile.c
src/CMakeLists.txt
src/cbor/arrays.c
src/cbor/bytestrings.c
src/cbor/internal/memory_utils.c
src/cbor/internal/memory_utils.h
src/cbor/maps.c
src/cbor/serialization.c
src/cbor/strings.c
test/bad_inputs_test.c

Fixes problems revealed by #16, where big enough size header could would overflow `size_t` when multiplied by the size of in-memory representation of subitems.
This is a major attack vector that allows an attacker to crash any existing libcbor client application.

Huge headers arithmetic overflow fixes

---

doc/source/api/item_reference_counting.rst
doc/source/api/type_6.rst
doc/source/conf.py
doc/source/requirements.txt
src/cbor/common.h

This fixes the latest batch of Sphinx/Breathe incompatibilities, as well as some minor issues in the docs themselves

Fix docs yet again

---

CMakeLists.txt

The current `CMakeLists.txt` require version 3.2 while 2.8 is enough.  
This change is required to build `libcbor` on Ubuntu 14.02 LTS.

CMakeLists.txt: Reduce required CMake version

---

src/cbor/common.c

If you made decref your object when refcount is "0" you need to incref it two times and decref to deallocate. Otherwise, it will leak. For me, this kind of behavior was unexpected

Add assert on decref

---

src/cbor/data.h
src/cbor/streaming.c
test/assertions.c
test/assertions.h
test/cbor_stream_decode_test.c

This PR adds the minimum number of bytes required by cbor_stream_decode to continue parsing when that function returns CBOR_DECODER_NEDATA as the status in the cbor_decoder_result.
This is useful when using a byte stream transport such as a raw TCP socket or UNIX pipe and blocking I/O.
I'm not sure if this is the best way to expose this information in the API, but it seemed to do the trick.

CBOR_DECODER_NEDATA: return required bytes

---

src/CMakeLists.txt

Without this patch, when building with `make -j1`
cmake would create and install two shared libraries
`libcbor.so` and `libcbor.so.0.0.0`
instead of creating `libcbor.so` as a symlink.
This broke verification of reproducible builds.
See https://reproducible-builds.org/ for why this matters.
Also, (like before) do not install libcbor.a
because static linking is bad for maintainability
(because all programs have to be re-built with fixed libraries)
This PR was done while working on reproducible builds for openSUSE.

Do not build two shared libraries

---

examples/streaming_parser.c

Basically, the width specifier in the format string caused printf to
read outside the buffer.
Fix by using strndup so we get a guaranteed null terminated buffer.
Fixes issue #67

Do not read from unallocated memory

---

CHANGELOG.md
misc/hooks/pre-commit
src/cbor/arrays.c
src/cbor/bytestrings.c
src/cbor/maps.c
src/cbor/strings.c
test/cbor_serialize_test.c
test/memory_allocation_test.c

Fix possible memory corruption bug on repeated cbor_(byte)string_add_chunk calls with intermittently failing realloc calls

---

src/cbor.c

Libraries shouldn't be printing things to stdout, it should be up to callers if they want to.

Remove printf

---

oss-fuzz/build.sh
oss-fuzz/cbor_load_fuzzer.cc

Not integrated into the libcbor build system, but the script can be used by itself if you set all the right env vars.

OSS-Fuzz fuzzer and build script

---

.travis-qemu.sh
clang-format.sh

Fixes for #104 :
- `clang-format` output is set to verbose
- use `git diff-index` to check uncommited changes

Improve ci

---

README.md

This makes the file ASCII-only

Use hyphen-minus (-) instead of en-dash

---

CHANGELOG.md
CMakeLists.txt
test/CMakeLists.txt
test/memory_allocation_test.c

Always be -pedantic to catch similar issues faster, there is no reason not to be.
Fixes #128

Fix memory_allocation_test w/o custom allocators

---

CHANGELOG.md
doc/source/getting_started.rst
src/CMakeLists.txt

A (hopefully) better attempt to fix #52

Shared lib versioning fix

---

CMakeLists.txt

See PJK/libcbor#140 for the context of this PR.
This definitely fixes the build failure on Ubuntu xenial.
Please **do not merge** until I can confirm that this approach actually enables LTO with newer versions of CMake. I haven't been able to confirm that LTO is being used.

integrate with CMake's LTO support

---

src/CMakeLists.txt
src/allocators.c
src/cbor.h
src/cbor/arrays.h
src/cbor/bytestrings.h
src/cbor/callbacks.c
src/cbor/callbacks.h
src/cbor/common.h
src/cbor/data.h
src/cbor/encoding.h
src/cbor/floats_ctrls.h
src/cbor/ints.h
src/cbor/maps.h
src/cbor/serialization.h
src/cbor/streaming.h
src/cbor/strings.h
src/cbor/tags.h

Currently, it always build both static and shared libs with the same name, which leads to name collision on Windows. The static library `cbor.a` replaces the symbol archive `cbor.a`.
This PR fix this problem:
- Build shared lib or static lib, not both at once. Use [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) to create the shared library.
- Export symbols with `cbor_export.h` header (generated by CMake) and `CBOR_EXPORT` macros.
Fix conan-io/conan-center-index#2578

Fix shared build

---

CHANGELOG.md
src/cbor.c
src/cbor/data.h
src/cbor/streaming.c
test/assertions.c
test/assertions.h
test/cbor_stream_decode_test.c
test/stream_expectations.c
test/stream_expectations.c.erb
test/stream_expectations.h

* Remove `CBOR_DECODER_EBUFFER` as it was never used and provides no benefit over NEDATA
* Change `cbor_decoder_result.required` to correctly account for all the data needed to proceed
* Add test coverage
* Improve comments & documentation
* Minor code cleanup
Closes #106

Improve cbor_stream_decode interface

---

src/cbor/common.h
src/cbor/internal/encoders.c
src/cbor/internal/loaders.c
src/cbor/internal/loaders.h

Add _CBOR_UNUSED for MSVC, fix a few warnings

---

CMakeModules/JoinPaths.cmake
src/CMakeLists.txt
src/libcbor.pc.in

It is not generally true that `CMAKE_INSTALL_<dir>` variables are relative paths:
https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files
When they are absolute, it leads to broken paths with duplicated prefix.

build: Fix pkg-config paths

---

oss-fuzz/cbor_load_fuzzer.cc

Now that the dataflow config for `libcbor` in `oss-fuzz` has been disabled (https://github.com/google/oss-fuzz/issues/3613), we can add back the heap limit size constraint to prevent out-of-memory fuzzing report.

Roll forward the heap allocation limit

---

src/cbor/internal/builder_callbacks.c

The missing of these checks might cause null pointer dereferencing.

add missing CHECK_RES calls

---

src/cbor/maps.h

Fixes the doc output for `cbor_new_indefinite_map()`

Remove invalid param for cbor_new_indefinite_map()

---

CHANGELOG.md
src/cbor/serialization.c
src/cbor/serialization.h
test/cbor_serialize_test.c

In my case I don't care exactly how many bytes were allocated, I just need the number of bytes the CBOR item serialized to.

Make the buffer_size optional in cbor_serialize_alloc()

---

.circleci/config.yml

Mac builds are much more expensive and platform-specific breakage is quite unlikely

Only run OSX CI on master and when linux job succeeded

---

CHANGELOG.md
src/cbor/encoding.c
test/float_ctrl_encoders_test.c

Encoding of half-float values that is in range of denormalized numbers had been trimmed the whole mantissa bits.
This patch improves it by reflecting some bits to the encoded value.
Some examples:
```
binary32  before  after   before     after
38000000  0x0200  0x0200  3.0518e-5  3.0518e-5
38004000  0x0200  0x0201  3.0518e-5  3.0577e-5
38008000  0x0200  0x0202  3.0518e-5  3.0637e-5
387f8000  0x0200  0x03fe  3.0518e-5  6.0916e-5
387fc000  0x0200  0x03ff  3.0518e-5  6.0976e-5
```
I used "round half away from zero" instead of "round to even" because it is simple and doesn't need an execution branch.

Half-float preserve more bits for denormals

---

src/cbor/streaming.c

Some compiler will emit a warning when using brace init lists (with `-Wall -Wextra`). Using C99 designated initializers ensure that other fields are zero'ed.
```
/home/markand/dev/github/libcbor/src/cbor/streaming.c:539:22: warning: missing initializer for field ‘required’ of ‘struct cbor_decoder_result’ [-Wmissing-field-initializers]
539 |       return (struct cbor_decoder_result){0, CBOR_DECODER_ERROR};
```

Use designated initializers to avoid a warning about missing fields.

---

src/cbor/internal/builder_callbacks.c
test/memory_allocation_test.c

Return values of `cbor_array_push`, `_cbor_map_add_key` and `_cbor_map_add_value` are unchecked. An unchecked `false` return value here implies potential out-of-bound memory access.
No
No
No
No

Fails gracefully when allocation fails during array/map construction

---

src/cbor/encoding.c

Address GCC warning:
_deps/libcbor-src/src/cbor/encoding.c:164:51: warning: suggest parentheses around arithmetic in operand of '|' [-Wparentheses]

Add parenthesis with | operator

---

CHANGELOG.md
src/cbor/bytestrings.c
src/cbor/internal/builder_callbacks.c
test/memory_allocation_test.c

The passed `chunk` is not freed when `cbor_bytestring_add_chunk` returns `false`.
No
No
No
No

Fixes memory leak in `cbor_bytestring_add_chunk`

---

examples/bazel/src/hello.h
examples/cjson2cbor.c
examples/create_items.c
examples/hello.c
examples/readfile.c
examples/sort.c
examples/streaming_array.c
examples/streaming_parser.c
src/cbor/arrays.c
src/cbor/arrays.h
src/cbor/bytestrings.c
src/cbor/bytestrings.h
src/cbor/floats_ctrls.c
src/cbor/floats_ctrls.h
src/cbor/internal/stack.c
src/cbor/internal/stack.h
src/cbor/ints.c
src/cbor/ints.h
src/cbor/maps.c
src/cbor/maps.h
src/cbor/strings.c
src/cbor/strings.h
test/cbor_serialize_test.c
test/copy_test.c
test/float_ctrl_encoders_test.c
test/fuzz_test.c
test/memory_allocation_test.c
test/stack_over_limit_test.c
test/stream_expectations.c
test/stream_expectations.h

Clang 15 has become more strict about prototypes of functions without arguments in C, showing many warnings similar to:
src/cbor/maps.h:49:49: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
CBOR_EXPORT cbor_item_t *cbor_new_indefinite_map();
^
void
This is because in C, functions declared or defined with () are considered old-style functions with variadic arguments. (Although these will likely be finally removed in C23.)
Fix the warnings by using `(void)` for each of the declarations and definitions. This also fixes two incorrect invocations of `cbor_new_indefinite_map(void)` in the tests.
(Note: this has been submitted as a follow-up of https://bugs.freebsd.org/268417, for the FreeBSD port of libcbor. The libfido2 port that …

Fix clang 15 -Wstrict-prototype warnings

---

.circleci/config.yml
test/assertions.c
test/assertions.h
test/cbor_stream_decode_test.c
test/stream_expectations.c
test/stream_expectations.h

Prerequisite/preparation for https://github.com/PJK/libcbor/issues/231

Reenable memcheck on CI and improve string/bytestring streaming decoding test

---

.circleci/config.yml
CMakeLists.txt

- For now keeping coveralls on gcov
- Handy for OSX development

Add code coverage tooling for clang

---

.circleci/config.yml

Broken in https://github.com/PJK/libcbor/pull/238/files because `ctest -T coverage` doesn't automatically run the testsuite

Fix CI code coverage reporting

---

appveyor.yml

- Use 2022 VS
- Run a single build on PRs (Appveyor was often the blocking check)
- Run both x84 and x64 builds

Update, simplify, and speed up Windows CI

---

appveyor.yml

The branch-specific config was still triggering the big build on all PRs (https://ci.appveyor.com/project/PJK/libcbor/builds/45784768) because they go to "master" :(

Trim down Appveyor config

---

CHANGELOG.md
src/cbor/internal/builder_callbacks.c
test/callbacks_test.c

Same as https://github.com/PJK/libcbor/pull/242

Fix potential memory leak in cbor_builder_string_callback 

---

CHANGELOG.md
src/cbor.c
src/cbor.h
src/cbor/arrays.h
src/cbor/bytestrings.h
src/cbor/common.h
src/cbor/encoding.h
src/cbor/floats_ctrls.h
src/cbor/internal/builder_callbacks.c
src/cbor/internal/encoders.h
src/cbor/internal/loaders.h
src/cbor/internal/memory_utils.h
src/cbor/internal/stack.h
src/cbor/internal/unicode.h
src/cbor/ints.h
src/cbor/maps.h
src/cbor/serialization.h
src/cbor/streaming.h
src/cbor/strings.h
src/cbor/tags.h
test/callbacks_test.c

First step towards https://github.com/PJK/libcbor/issues/247
Marking all functions where ignoring the return value 
- is dangerous, or
- doesn't make sense since the function has no other effect (indicates incorrect usage)

Add [[nodiscard]]-like macro and fix a few violations

---

CHANGELOG.md
doc/source/api/encoding.rst
src/cbor/internal/memory_utils.c
src/cbor/internal/memory_utils.h
src/cbor/serialization.c
src/cbor/serialization.h
src/cbor/strings.h
test/cbor_serialize_test.c
test/memory_utils_test.c

- Prerequisite for fixing the repeated reallocation in cbor_serialize_alloc, which is super wasteful and ugly
- Adding as a part of the public API since it seems generally helpful
- Also add some new related test coverage

Add cbor_serialized_size

---

CHANGELOG.md
README.md
doc/source/using.rst
examples/cjson2cbor.c
src/cbor/serialization.c
src/cbor/serialization.h
test/cbor_serialize_test.c

- The allocate-serialize-retry loop was ugly and inefficient, especially for large items that might take a number of tries to succeed
- Will also waste less memory
- The downside is that the old API doesn't match the new logic so well, the return value and the output parameter are redundant now. Given the number of clients (https://github.com/search?q=cbor_serialize_alloc&type=code), I will keep the function as-is for now since it is backwards compatible

Rework cbor_serialize_alloc to allocate exact buffer size upfront

---

src/cbor.c
src/cbor/arrays.c
src/cbor/bytestrings.c
src/cbor/common.c
src/cbor/common.h
src/cbor/encoding.c
src/cbor/floats_ctrls.c
src/cbor/internal/builder_callbacks.c
src/cbor/ints.c
src/cbor/maps.c
src/cbor/serialization.c
src/cbor/strings.c
src/cbor/tags.c
test/cbor_serialize_test.c
test/float_ctrl_encoders_test.c
test/float_ctrl_test.c
test/memory_utils_test.c

- Make cbor_serialize_alloc always fill allocation size output param, even on failure
- Minor refactoring

Improve edge case test coverage; fix minor bugs

---

.circleci/config.yml
src/cbor/common.h
src/cbor/serialization.c
test/float_ctrl_test.c

Small bug introduced in https://github.com/PJK/libcbor/pull/254 -- tests wouldn't compile in release mode since _cbor_enable_assert is no defined.

Fix CBOR_ASSERT test behavior in release builds, add release CI, minor release mode imrovements

---

CHANGELOG.md
src/cbor/serialization.c
test/cbor_serialize_test.c

Fixes #259 
Huge thanks for @martelletto for quickly reporting this!
Minor release will follow to patch v0.10

Fix cbor_serialized_size for zero-len strings

---

README.md

According to documentation:
* https://libcbor.readthedocs.io/en/latest/getting_started.html#building-installing-libcbor
> CBOR_CUSTOM_ALLOC has been removed. Custom allocators (historically a controlled by a build flag) are always enabled.
Documentation seems conflicting.

README: Remove CBOR_CUSTOM_ALLOC flag

---

.cirrus.yml

Test on FreeBSD 12.4 and FreeBSD 13.2, the two currently supported releases.
Add CI for FreeBSD using Cirrus-CI
Example run: https://cirrus-ci.com/task/6708320812138496
I did not see a changelog entry for CircleCI, but if this PR is welcome and a changelog entry is desired I will push an update.

Add Cirrus-CI config file to build & test on FreeBSD

---

CMakeLists.txt

allow `CMAKE_SKIP_INSTALL_ALL_DEPENDENCY` to be changed so that a `cmake -Dsomeoption -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=OFF  && cmake --build . --target install` can build and install
this does not introduce any new behaviour aside from allowing to override the option in the `cmake` configuration step.

make CMAKE_SKIP_INSTALL_ALL_DEPENDENCY an option

---

src/cbor.c

Add data as hex string in `cbor_describe` for type `CBOR_TYPE_BYTESTRING`
I did find it useful to have the data printed out just like for `CBOR_TYPE_STRING`.

Print CBOR_TYPE_BYTESTRING value as hex string

---

CHANGELOG.md
src/cbor.c
test/pretty_printer_test.c

Follow up to https://github.com/PJK/libcbor/pull/281

Improve cbor_describe formatting and code quality

---

CHANGELOG.md
src/cbor.c
src/cbor/internal/builder_callbacks.c
src/cbor/internal/unicode.c
src/cbor/internal/unicode.h
src/cbor/strings.c
src/cbor/strings.h
test/cbor_serialize_test.c
test/pretty_printer_test.c
test/string_test.c

- Fix value not being set by `cbor_string_set_handle`
- Do not fail parsing on a well-formed (https://www.rfc-editor.org/rfc/rfc8949#section-3.1-2.8 says "A string containing an invalid UTF-8 sequence is well-formed but invalid") to be consistent in the parsing and manipulation APIs
- Document the new behavior

Fix UTF-8 codepoint counting in cbor_string_set_handle and parsing

---

.cirrus.yml

FreeBSD 14.0 was released recently.  FreeBSD 12.4 is EOL at the end of 2023.
FreeBSD 14.0 added to Cirrus-CI. FreeBSD 12.4 removed from Cirrus-CI.

CI: Add FreeBSD 14.0 and drop FreeBSD 12.4

---

CHANGELOG.md
src/cbor/streaming.c
test/cbor_stream_decode_test.c
test/tag_test.c

The decoder would only accept tag values in the protected range that were registered when it was originally written. See inline comment for accepting all values is better
Fixes https://github.com/PJK/libcbor/issues/307

Support decoding all tag values

---

CMakeLists.txt

It appears that a typo was introduced in CMakeLists.txt over 2 years ago in commit a4535264d046bf9713ef58a5a5eb9fc12384aa91 that effectively disabled the code coverage option. I fixed it.

Fixed code coverage option typo in CMakeLists.txt

---

.circleci/config.yml
CHANGELOG.md
doc/source/api/type_7_floats_ctrls.rst
doc/source/standard_conformance.rst
src/cbor/encoding.c
src/cbor/encoding.h
src/cbor/internal/encoders.c
src/cbor/internal/loaders.c
test/CMakeLists.txt
test/float_ctrl_encoders_test.c

Fixes #271 
Fixes #329 
I realized that if we are not in IEEE 754, the cast of internal representation to bytes is broken, but IUUC mips in general should bei compliant-ish...

Fix NaN handling on mips/mipsel and Windows; disable value propagation for signaling NaNs; add mips CI

---

examples/cbor2cjson.c

The cbor2cjson.c example contains a call to cbor_array_get, which increments the reference counter, that is not paired with a cbor_move or reference decrement.
I borrowed the cbor_to_cjson function in some test code that was exhibiting a memory leak, until I added a cbor_move call:
https://github.com/whitehse/testing/blob/master/ipfix/ipfix_server.c
There are two kinds of arrays in my test data. I don't know if one or both kinds are triggering an issue:
* An array of maps - success &= cbor_array_push(array_of_templates, cbor_move(template));
* An array of uint16's - success &= cbor_array_push(array_of_fields, cbor_move(cbor_build_uint16(field_type)));
Since this is example code, I have not updated any tests, documentation, or the CHANGELOG. There are no security or performance …

In cbor2cjson.c example, add missing cbor_move to cbor_array_get call

---

CMakeLists.txt
src/CMakeLists.txt

adds the PROJECT_BINARY_DIR include directly to the cbor target instead of using `include_directories`.
`include_directories` is limited to the current CMakeLists.txt and anything loaded under it, this makes it impossible to use libcbor as a submodule or via FetchContent since the include path never gets propagated.

include project directory with target instead of globally

---

src/cbor.c
test/cbor_serialize_test.c

The two uses of `#pragma clang` in the tree don't do anything and cause GCC to whine about unknown pragmas in some cases so remove them.
Noticed the `push` when trying to build FreeBSD and it's embedded copy of libcbor with GCC 13.
I've not updated the CHANGELOG as these commits don't have any functional effect.

Remove no-op pragma clang lines

---

CHANGELOG.md
misc/update_version.py
release.sh

Update changelog, improve release script to automate version bump PRs

---

CMakeLists.txt

Fixed https://github.com/PJK/libcbor/issues/351
What changes and why

Set cmake_minimum_required to 3.5

---

test/map_test.c

Fixes https://github.com/PJK/libcbor/issues/66

Add a test for malformed definite maps

---

src/cbor/arrays.h

Add a documentation for the reference count in cbor_array_set().
Because cbor_array_set() calls cbor_array_push() or cbor_array_replace(), the reference count increases.

Add a doc for the reference count in cbor_array_set().
